library(ggplot2)
library(googleVis)
library(dplyr)

t = read.csv("/Users/abhijitj/Downloads/india-data/1State-wiseTotalPopulation_done.csv")
t <- subset(t, select = -c(X))
t <- t %>% rename_(.dots=setNames(names(.), (gsub("1.0", "1", names(.)))))
t <- t %>% rename_(.dots=setNames(names(.), (gsub("X", "", names(.)))))
colnames(t)[1] <- c("States")
library(reshape2)
state_population <- melt(t, id.vars = "States", variable.name = "Years", value.name = "Popoulation", na.rm = TRUE)
l = read.csv("/Users/abhijitj/Downloads/india-data/86State-wiseLiteracyRate_done.csv")
l <- subset(l, select = -c(X, X.1, X.2, X.3, X.4, X.5))
l <- l%>% rename_(.dots=setNames(names(.), (gsub("1.0", "1", names(.)))))
l <- l%>% rename_(.dots=setNames(names(.), (gsub("X", "", names(.)))))
colnames(l)[1] <- c("States")
state_population$Years <- as.numeric(as.character(state_population$Years))
state_population$Popoulation <- as.numeric(as.character(state_population$Popoulation))
state_literacy <- melt(l, id.vars = "States", variable.name = "Years", value.name = "Literacy", na.rm = TRUE)
state_literacy$Years <- as.numeric(as.character(state_literacy$Years))
state_literacy$Literacy <- as.numeric(as.character(state_literacy$Literacy))
fdata <- left_join(state_population, state_literacy, by=c("States", "Years"))

a = read.csv("/Users/abhijitj/Downloads/india-data/3State-wiseAvailabilityofPower_done.csv")
a<- subset(a, select = -c(X))
a <- a%>% rename_(.dots=setNames(names(.), (gsub("\\.0.", "", names(.)))))
a <- a%>% rename_(.dots=setNames(names(.), (gsub("\\.1.", "", names(.)))))
a <- a%>% rename_(.dots=setNames(names(.), (gsub("X", "", names(.)))))
colnames(a)[1] <- c("States")
state_avl_power <- melt(a, id.vars = "States", variable.name = "Years", value.name = "Available Power", na.rm = TRUE)
state_avl_power$Years <- as.numeric(as.character(state_avl_power$Years))
state_avl_power$States <- as.character(state_avl_power$States)
state_avl_power$`Available Power` <- as.numeric(as.character(state_avl_power$`Available Power`))

r = read.csv("/Users/abhijitj/Downloads/india-data/5State-wisePowerRequirement_done.csv")
r<- subset(r, select = -c(X))
r <- r%>% rename_(.dots=setNames(names(.), (gsub("\\.0.", "", names(.)))))
r <- r%>% rename_(.dots=setNames(names(.), (gsub("\\.1.", "", names(.)))))
r <- r%>% rename_(.dots=setNames(names(.), (gsub("X", "", names(.)))))
colnames(r)[1] <- c("States")
state_req_power <- melt(r, id.vars = "States", variable.name = "Years", value.name = "Required Power", na.rm = TRUE)
state_req_power$Years <- as.numeric(as.character(state_req_power$Years))
state_req_power$States <- as.character(state_req_power$States)
state_req_power$`Required Power` <- as.numeric(as.character(state_req_power$`Required Power`))

fdata <- left_join(fdata, state_avl_power, by = c("States", "Years"))
fdata <- left_join(fdata, state_req_power, by = c("States", "Years"))
chart<- gvisMotionChart(fdata, idvar = "States", timevar = "Years", colorvar = "Literacy", xvar = "Available Power", yvar = "Required Power", sizevar="Popoulation", chartid="Population_Literacy_Data")
plot(chart)
#print(chart, "chart", file="//Users/abhijitj/Downloads/india-data/Population_vs_Literacy.html")